# Generated by Django 4.2.1 on 2023-05-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'data', 'verbose_name_plural': 'data'},
        ),
    ]
