# Generated by Django 4.2.1 on 2023-05-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_category_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='published_at',
            field=models.DateField(auto_now=True),
        ),
    ]
