# Generated by Django 4.2.1 on 2023-05-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_apply_jobrel'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applied_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.FileField(null=True, upload_to='apply/'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='web',
            field=models.URLField(null=True),
        ),
    ]
