# Generated by Django 4.2.1 on 2023-05-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_apply_applied_at_alter_apply_cv_alter_apply_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='jobrel',
        ),
        migrations.AddField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
