# Generated by Django 4.2.1 on 2023-05-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_city'),
        ('job', '0013_job_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
