# Generated by Django 4.2.1 on 2023-05-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_city'),
        ('job', '0014_job_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
