# Generated by Django 4.2.1 on 2023-05-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_job_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='profile',
        ),
    ]
