# Generated by Django 4.2.1 on 2023-05-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_alter_category_options_remove_job_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'verbose_name_plural': 'applies'},
        ),
    ]
