# Generated by Django 4.2.1 on 2023-05-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_alter_profile_city_delete_city'),
        ('job', '0019_alter_apply_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
    ]
