# Generated by Django 4.2.1 on 2023-05-17 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_city'),
        ('job', '0020_job_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='address',
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
        ),
    ]
