# Generated by Django 4.2.1 on 2023-05-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_remove_job_address_job_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
    ]
