# Generated by Django 4.2.1 on 2023-05-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_address_profile_city'),
        ('job', '0022_remove_job_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
        ),
    ]
