# Generated by Django 4.2.1 on 2023-05-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_alter_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Vacancy',
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(default=1),
        ),
    ]
